package com.aiyu.furniture.utils;

import com.aiyu.furniture.core.database.model.Category;
import com.aiyu.furniture.core.database.model.Furniture;

import java.util.ArrayList;
import java.util.List;

public class Items {

    public static List<Furniture> getFurnitureList() {
        List<Furniture> furnitureList = new ArrayList<>();

        // Chairs
        furnitureList.add(new Furniture("Decade Chair", "Modern outdoor dining chair", "https://www.bludot.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/o/u/outdoor_dining_chairs_decade_01_web.jpg", Category.CHAIR, "https://www.bludot.com/outdoor/dining-chairs/decade-outdoor-dining-chair.html"));
        furnitureList.add(new Furniture("Dibs Chair", "Compact and comfortable accent chair", "https://www.bludot.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/i/living_chairs_dibs_01_web.jpg", Category.CHAIR, "https://www.bludot.com/living/chairs/dibs-chair.html"));
        furnitureList.add(new Furniture("Made You Look Outdoor Chair", "Stylish and durable outdoor chair", "https://www.bludot.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/o/u/outdoor_lounge_chairs_madeyoulook_01_web.jpg", Category.CHAIR, "https://www.bludot.com/outdoor/lounge-chairs/made-you-look-outdoor-chair.html"));
        furnitureList.add(new Furniture("Amelia Grand Chair", "Rounded and plush chair inspired by the 70s", "https://joybird.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/m/amelia-grand-chair-key-largo-zenith-teal_1.jpg", Category.CHAIR, "https://joybird.com/chairs/accent-chairs/amelia-grand-chair/"));
        furnitureList.add(new Furniture("Bell Chair", "Modern accent chair with a unique shape", "https://joybird.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/e/bell-chair-royale-peacock_1.jpg", Category.CHAIR, "https://joybird.com/chairs/accent-chairs/bell-chair/"));
        furnitureList.add(new Furniture("Gabriola 34\" Lounge Chair", "Ivory bouclé lounge chair with a soft texture", "https://www.article.com/assets/img/live/product/1398__1__original_desktop.jpg", Category.CHAIR, "https://www.article.com/product/1398/gabriola-34-lounge-chair-ivory-boucle"));
        furnitureList.add(new Furniture("Joshpal Upholstered Accent Chair (Set of 2)", "Modern upholstered accent chairs sold as a set", "https://secure.img1-fg.wfcdn.com/im/39619795/resize-h445-w445%5Ecompr-r85/1737/173797993/joshpal-upholstered-accent-chair-set-of-2.jpg", Category.CHAIR, "https://www.wayfair.com/furniture/pdp/george-oliver-joshpal-upholstered-accent-chair-set-of-2-w007695081.html"));
        furnitureList.add(new Furniture("Foldable Round Saucer Chair", "Portable lounge chair suitable for small spaces", "https://secure.img1-fg.wfcdn.com/im/88478837/resize-h445-w445%5Ecompr-r85/2132/213214799/foldable-round-saucer-chair-portable-dorm-chair-lounge-chair-accent-chair-for-bedroom-living-room.jpg", Category.CHAIR, "https://www.wayfair.com/furniture/pdp/monibloom-foldable-round-saucer-chair-portable-dorm-chair-lounge-chair-accent-chair-for-bedroom-living-room-monb1002.html"));
        furnitureList.add(new Furniture("Hachmann Faux Leather Slipper Chair", "Armless slipper chair with a faux leather finish", "https://secure.img1-fg.wfcdn.com/im/58868651/resize-h445-w445%5Ecompr-r85/1674/167401464/hachmann-faux-leather-slipper-chair.jpg", Category.CHAIR, "https://www.wayfair.com/furniture/pdp/17-stories-hachmann-faux-leather-slipper-chair-w004687328.html"));
        furnitureList.add(new Furniture("Leopold's Chair & Ottoman Set", "Classic chair and ottoman with timeless design", "https://www.stickley.com/wp-content/uploads/2024/01/500-401_402_Lifestyle_01.jpg", Category.CHAIR, "https://www.stickley.com/collections/armchairs-accent-chairs/products/leopolds-chair-ottoman-set"));
        furnitureList.add(new Furniture("Sidney Chair", "Elegant chair with a sophisticated silhouette", "https://www.stickley.com/wp-content/uploads/2024/01/500-451_Lifestyle_01.jpg", Category.CHAIR, "https://www.stickley.com/collections/armchairs-accent-chairs/products/sidney-chair"));
        furnitureList.add(new Furniture("Wharton Tufted Chair", "Luxurious tufted chair with a classic appeal", "https://www.stickley.com/wp-content/uploads/2024/01/500-452_Lifestyle_01.jpg", Category.CHAIR, "https://www.stickley.com/collections/armchairs-accent-chairs/products/wharton-tufted-chair"));
        furnitureList.add(new Furniture("Redmond Chair", "Comfortable accent chair with a modern design", "https://slumberland.scene7.com/is/image/Slumberland/G100202015_001_01?$s7product$", Category.CHAIR, "https://www.slumberland.com/p/redmond_chair/100202015"));
        furnitureList.add(new Furniture("Riles Chair", "Stylish chair with a sleek and contemporary look", "https://slumberland.scene7.com/is/image/Slumberland/G100202021_001_01?$s7product$", Category.CHAIR, "https://www.slumberland.com/p/riles_chair/100202021"));
        furnitureList.add(new Furniture("Cormic Swivel Accent Chair", "Swivel chair with a cozy and inviting feel", "https://slumberland.scene7.com/is/image/Slumberland/G100202029_001_01?$s7product$", Category.CHAIR, "https://www.slumberland.com/p/cormic_swivel_accent_chair/100202029"));
        furnitureList.add(new Furniture("Blake Slope Arm Chair and a Half", "Oversized chair with a comfortable slope arm design", "https://www.bassettfurniture.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-bassett-master/default/dw03a69237/images/hi-res/4739-01_RS.jpg?sw=800&sh=800&sm=fit", Category.CHAIR, "https://www.bassettfurniture.com/living/chairs/accent-chairs/blake-slope-arm-chair-and-a-half-4739-01.html"));
        furnitureList.add(new Furniture("Stockten English Arm Skirted Chair", "Elegant chair with a classic English arm and skirted base", "https://www.bassettfurniture.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-bassett-master/default/dw5929158d/images/hi-res/4950-01_RS.jpg?sw=800&sh=800&sm=fit", Category.CHAIR, "https://www.bassettfurniture.com/living/chairs/accent-chairs/stockten-english-arm-skirted-chair-4950-01.html"));
        furnitureList.add(new Furniture("Stockten English Arm Chair", "Classic chair with an English arm design", "https://www.bassettfurniture.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-bassett-master/default/dw9c01562b/images/hi-res/4950-10_RS.jpg?sw=800&sh=800&sm=fit", Category.CHAIR, "https://www.bassettfurniture.com/living/chairs/accent-chairs/stockten-english-arm-chair-4950-10.html"));
        furnitureList.add(new Furniture("Meyer Chair", "Comfortable chair with a casual and inviting style", "https://www.la-z-boy.com/dw/image/v2/BLLZ_PRD/on/demandware.static/-/Sites-lazboy-master/default/dw22415165/images/hi-res/017503_140501_Meyer_Chair_3Q.jpg?sw=800&sh=800&sm=fit", Category.CHAIR, "https://www.la-z-boy.com/p/stationary-chairs/meyer-chair/_/R-017503"));
        furnitureList.add(new Furniture("Noah Chair", "Stylish chair with a clean and modern silhouette", "https://www.la-z-boy.com/dw/image/v2/BLLZ_PRD/on/demandware.static/-/Sites-lazboy-master/default/dw7616191b/images/hi-res/017783_140501_Noah_Chair_3Q.jpg?sw=800&sh=800&sm=fit", Category.CHAIR, "https://www.la-z-boy.com/p/stationary-chairs/noah-chair/_/R-017783"));
        furnitureList.add(new Furniture("Kennedy Chair", "Classic chair with a timeless and elegant design", "https://www.la-z-boy.com/dw/image/v2/BLLZ_PRD/on/demandware.static/-/Sites-lazboy-master/default/dw641f3d3f/images/hi-res/019811_140501_Kennedy_Chair_3Q.jpg?sw=800&sh=800&sm=fit", Category.CHAIR, "https://www.la-z-boy.com/p/stationary-chairs/kennedy-chair/_/R-019811"));
        furnitureList.add(new Furniture("Willarae Chair and a Half", "Spacious chair and a half for extra comfort", "https://cdn.shopify.com/s/files/1/0274/8238/1418/products/4690023_1_1024x1024.jpg?v=1660859078", Category.CHAIR, "https://www.robertsfurnitureonline.com/products/willarae-chair-and-a-half"));
        furnitureList.add(new Furniture("Modmax Armless Chair", "Sleek and armless chair with a modern vibe", "https://cdn.shopify.com/s/files/1/0274/8238/1418/products/8000423_1_1024x1024.jpg?v=1660859073", Category.CHAIR, "https://www.robertsfurnitureonline.com/products/modmax-armless-chair"));
        furnitureList.add(new Furniture("Lango Chair", "Comfortable chair with a stylish and inviting design", "https://cdn.shopify.com/s/files/1/0274/8238/1418/products/4020023_1_1024x1024.jpg?v=1660859070", Category.CHAIR, "https://www.robertsfurnitureonline.com/products/lango-chair"));
        furnitureList.add(new Furniture("Papasan Bowl Chair", "Iconic bowl chair with a soft and cozy cushion", "https://www.athome.com/dw/image/v2/BBYY_PRD/on/demandware.static/-/Sites-athome-master/default/dwf3049409/images/124281930.jpg?sw=1200&sh=1200&sm=fit", Category.CHAIR, "https://www.athome.com/papasan-bowl-chair-(papasan-chair-base-sold-separately)/124281930.html"));
        furnitureList.add(new Furniture("Crosby St. Sawyer Swivel Faux Leather Accent Chair", "Swivel accent chair with a stylish faux leather upholstery", "https://www.athome.com/dw/image/v2/BBYY_PRD/on/demandware.static/-/Sites-athome-master/default/dw770880b7/images/124292524.jpg?sw=1200&sh=1200&sm=fit", Category.CHAIR, "https://www.athome.com/crosby-st.-sawyer-swivel-faux-leather-accent-chair,-grey/124292524.html"));
        furnitureList.add(new Furniture("Hadley Tufted Back Accent Chair", "Elegant accent chair with a comfortable tufted back", "https://www.athome.com/dw/image/v2/BBYY_PRD/on/demandware.static/-/Sites-athome-master/default/dw31f16779/images/124292533.jpg?sw=1200&sh=1200&sm=fit", Category.CHAIR, "https://www.athome.com/crosby-st.-hadley-tufted-back-accent-chair,-charcoal-grey/124292533.html"));
        furnitureList.add(new Furniture("Brynn Feather Filled Swivel Chair", "Comfortable swivel chair with feather-filled cushions", "https://www.worldmarket.com/dw/image/v2/BBYY_PRD/on/demandware.static/-/Sites-wm-master/default/dwf7b3b37d/images/38687_1.jpg?sw=1200&sh=1200&sm=fit", Category.CHAIR, "https://www.worldmarket.com/p/brynn-feather-filled-swivel-chair-charcoal-173478.html"));
        furnitureList.add(new Furniture("Papasan Chair Frame and Sherpa Cushion", "Classic papasan chair with a soft sherpa cushion", "https://www.worldmarket.com/dw/image/v2/BBYY_PRD/on/demandware.static/-/Sites-wm-master/default/dw0f9c8662/images/47084_1.jpg?sw=1200&sh=1200&sm=fit", Category.CHAIR, "https://www.worldmarket.com/p/papasan-chair-frame-and-sherpa-cushion-natural-188364.html"));
        furnitureList.add(new Furniture("Sophie Upholstered Swivel Chair", "Stylish upholstered swivel chair for any living space", "https://www.worldmarket.com/dw/image/v2/BBYY_PRD/on/demandware.static/-/Sites-wm-master/default/dwf09f840b/images/48094_1.jpg?sw=1200&sh=1200&sm=fit", Category.CHAIR, "https://www.worldmarket.com/p/sophie-upholstered-swivel-chair-slate-grey-192814.html"));
        furnitureList.add(new Furniture("Thomasville Wills Fabric Oversize Chair and Storage Ottoman", "Oversized fabric chair with a storage ottoman", "https://mobilecontent.costco.com/live/resource/img/static-us-tiles/chairs-1.jpg", Category.CHAIR, "https://www.costco.com/thomasville-wills-fabric-oversize-chair-and-storage-ottoman.product.1778848.html"));
        furnitureList.add(new Furniture("Truth Accent Chair", "Modern accent chair with a sleek design", "https://www.jordans.com/-/media/Jordan-s/2022/August/Truth-Accent-Chair/0000000000000000000000000000001260647.jpg?h=560&w=560&la=en&hash=C6C92A1E63115D95486B6E508D691E78", Category.CHAIR, "https://www.jordans.com/shop/living-room/chairs/armchairs/truth-accent-chair-1260647"));
        furnitureList.add(new Furniture("Twin Sleeper Chair", "Comfortable chair that converts into a twin bed", "https://www.jordans.com/-/media/Jordan-s/2023/October/Twin-Sleeper-Chair/0000000000000000000000000000001300074.jpg?h=560&w=560&la=en&hash=D4A629540A9081587F9B3A7A9530C7F0", Category.CHAIR, "https://www.jordans.com/shop/living-room/chairs/armchairs/twin-sleeper-chair-1300074"));
        furnitureList.add(new Furniture("Ventura Leather Chair & Storage Ottoman", "Leather chair with a matching storage ottoman", "https://www.jordans.com/-/media/Jordan-s/2023/October/Ventura-Leather-Chair-and-Storage-Ottoman/0000000000000000000000000000001300076.jpg?h=560&w=560&la=en&hash=06F6F94118416568215E5484887B628E", Category.CHAIR, "https://www.jordans.com/shop/living-room/chairs/armchairs/ventura-leather-chair-storage-ottoman-1300076"));
        furnitureList.add(new Furniture("Pipe Lounge Chair (swivel)", "Contemporary swivel lounge chair", "https://sintesi.design/image/cache/catalog/friends-founders/pipe-lounge-chair-swivel-friends-founders-1-1200x1200.jpg", Category.CHAIR, "https://www.savannah-bay.com/en/pipe-lounge-chair-swivel-by-friends-founders.html"));
        furnitureList.add(new Furniture("Hippo Lounge Chair", "Modern lounge chair with a unique design", "https://sintesi.design/image/cache/catalog/norr11/Hippo-Lounge-Chair-Norr11-1-1200x1200.jpg", Category.CHAIR, "https://www.savannah-bay.com/en/hippo-lounge-chair-by-norr11.html"));
        furnitureList.add(new Furniture("Fave Chair by Norr11 (Fabric)", "Comfortable fabric lounge chair", "https://sintesi.design/image/cache/catalog/norr11/Fave-Chair-Norr11-Fabric-1-1200x1200.jpg", Category.CHAIR, "https://www.savannah-bay.com/en/fave-chair-by-norr11-fabric.html"));
        furnitureList.add(new Furniture("Sealife Upholstered Recliner", "Comfortable upholstered recliner", "https://www.kirklands.com/img/homepage/012424/Sealife-Upholstered-Recliner-Homepage-Desktop.jpg", Category.CHAIR, "https://www.kirklands.com/product/Furniture/Living-Room-Furniture/Recliners/Sealife-Upholstered-Recliner/pc/2285/c/3060/sc/3061/201260.uts"));
        furnitureList.add(new Furniture("Garden Party Aubrey Accent Chair", "Stylish accent chair with a garden party theme", "https://www.kirklands.com/img/homepage/012424/Garden-Party-Aubrey-Accent-Chair-Homepage-Desktop.jpg", Category.CHAIR, "https://www.kirklands.com/product/Furniture/Living-Room-Furniture/Accent-Chairs/Garden-Party-Aubrey-Accent-Chair/pc/2285/c/3058/sc/2628/201253.uts"));
        return furnitureList;
    }
}